name: linux build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: "ubuntu-22.04"

    permissions:
      contents: read

    env:
      WEBSITEIP: ${{ secrets.WEBSITEIP }}
      PULLANDRESTART: ${{ secrets.PULLANDRESTART }}

    steps:
      - name: Send request lol
        run: |
          curl -X GET -H "Authorization:$PULLANDRESTART" http://$WEBSITEIP/pullAndRestart